apiVersion: batch/v1
kind: Job
metadata:
  name: ping
spec:
  template:
    spec:
      containers:
        - name: busybox
          image: busybox:latest
          command: ["ping", "geeksforgeeks.org"]
          imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 4
